aliases:
  android_docker: &android_docker
    docker:
      - image: circleci/android:api-28
  build_steps: &build_steps
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
    - run:
        name: Download dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
          - ~/.gradle
        key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
    - run:
        name: Build debug APK
        command: ./gradlew assembleDebug

version: 2
jobs:
  build:
    <<: *android_docker
    steps:
      - *build_steps
  deploy:
    <<: *android_docker
    steps:
      - *build_steps
      - run:
          name: Upload to DeployGate # Set DG_API_KEY in CircleCI
          command: |
            COMMIT_HASH=$(git log --format="%H" -n 1 | cut -c 1-8)
            APK_PATH=app/build/outputs/apk/debug/app-debug.apk
            USERNAME=nekonenene
            curl -F "file=@${APK_PATH}" -F "token=${DG_API_KEY}" -F "message=Build by CircleCI <${COMMIT_HASH}>" https://deploygate.com/api/users/${USERNAME}/apps

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires: [build]
          filters:
            branches:
              only: master
          context: deploygate
